export const cities =
[
    { "value": "Abu Baham", "label": "Abu Baham" },
    { "value": "Abu Saybi`", "label": "Abu Saybi`" },
    { "value": "Abu Qowah", "label": "Abu Qowah" },
    { "value": "Ad Dayr", "label": "Ad Dayr" },
    { "value": "Ad Diraz", "label": "Ad Diraz" },
    { "value": "Ad Dur", "label": "Ad Dur" },
    { "value": "Al Bid`ah", "label": "Al Bid`ah" },
    { "value": "Al Busaytin", "label": "Al Busaytin" },
    { "value": "Al Ghurayfah", "label": "Al Ghurayfah" },
    { "value": "Al Hajar", "label": "Al Hajar" },
    { "value": "Al Hamalah", "label": "Al Hamalah" },
    { "value": "Al Hidd", "label": "Al Hidd" },
    { "value": "Al Hujayr", "label": "Al Hujayr" },
    { "value": "Al Jubaylat", "label": "Al Jubaylat" },
    { "value": "Al Jufayr", "label": "Al Jufayr" },
    { "value": "Al Kharijiyah", "label": "Al Kharijiyah" },
    { "value": "Al Ma`amir", "label": "Al Ma`amir" },
    { "value": "Al Mahuz", "label": "Al Mahuz" },
    { "value": "Al Malikiyah", "label": "Al Malikiyah" },
    { "value": "Al Mamtalah", "label": "Al Mamtalah" },
    { "value": "Al Markh", "label": "Al Markh" },
    { "value": "Al Mukharqa", "label": "Al Mukharqa" },
    { "value": "Al Muqsha`", "label": "Al Muqsha`" },
    { "value": "Al Muwaylighah", "label": "Al Muwaylighah" },
    { "value": "Al Musalla", "label": "Al Musalla" },
    { "value": "Al Qadam", "label": "Al Qadam" },
    { "value": "Al Qal`ah", "label": "Al Qal`ah" },
    { "value": "Al Qaryah", "label": "Al Qaryah" },
    { "value": "Al Qudaybiyah", "label": "Al Qudaybiyah" },
    { "value": "Al Quful", "label": "Al Quful" },
    { "value": "Al Qurayyah", "label": "Al Qurayyah" },
    { "value": "Al Wasmiyah", "label": "Al Wasmiyah" },
    { "value": "Al `Adliyah", "label": "Al `Adliyah" },
    { "value": "Al `Akr", "label": "Al `Akr" },
    { "value": "Al `Amar", "label": "Al `Amar" },
    { "value": "An Na'im", "label": "An Na'im" },
    { "value": "An Nuwaydirat", "label": "An Nuwaydirat" },
    { "value": "Ar Rifa", "label": "Ar Rifa" },
    { "value": "Ar Rifa` al Gharbi", "label": "Ar Rifa` al Gharbi" },
    { "value": "Ar Rifa` ash Shamali", "label": "Ar Rifa` ash Shamali" },
    { "value": "Ar Rifa` ash Sharqi", "label": "Ar Rifa` ash Sharqi" },
    { "value": "Ar Rumaythah", "label": "Ar Rumaythah" },
    { "value": "Ar Ruq`ah", "label": "Ar Ruq`ah" },
    { "value": "As Sahlah al Fawqiyah", "label": "As Sahlah al Fawqiyah" },
    { "value": "As Sahlat al Hadriyah", "label": "As Sahlat al Hadriyah" },
    { "value": "As Sakhir", "label": "As Sakhir" },
    { "value": "As Salihiyah", "label": "As Salihiyah" },
    { "value": "As Salmaniyah", "label": "As Salmaniyah" },
    { "value": "Astan", "label": "Astan" },
    { "value": "Bani Jamrah", "label": "Bani Jamrah" },
    { "value": "Bilad Al Qadeem", "label": "Bilad Al Qadeem" },
    { "value": "Budaiya", "label": "Budaiya" },
    { "value": "Diyar Al Muharraq", "label": "Diyar Al Muharraq" },
    { "value": "Durrat Al Bahrain", "label": "Durrat Al Bahrain" },
    { "value": "Hawar Islands", "label": "Hawar Islands" },
    { "value": "Isa Town", "label": "Isa Town" },
    { "value": "Jidd Hafs", "label": "Jidd Hafs" },
    { "value": "Juffair", "label": "Juffair" },
    { "value": "Karranah", "label": "Karranah" },
    { "value": "Khalifa City", "label": "Khalifa City" },
    { "value": "Mahazza", "label": "Mahazza" },
    { "value": "Manama", "label": "Manama" },
    { "value": "Maqabah", "label": "Maqabah" },
    { "value": "Mina Salman", "label": "Mina Salman" },
    { "value": "Muqsha", "label": "Muqsha" },
    { "value": "Nad Al Hamra", "label": "Nad Al Hamra" },
    { "value": "North Sehla", "label": "North Sehla" },
    { "value": "Nuwaidrat", "label": "Nuwaidrat" },
    { "value": "Riffa", "label": "Riffa" },
    { "value": "Samaheej", "label": "Samaheej" },
    { "value": "Sanabis", "label": "Sanabis" },
    { "value": "Sar", "label": "Sar" },
    { "value": "Saar", "label": "Saar" },
    { "value": "Seef", "label": "Seef" },
    { "value": "South Sehla", "label": "South Sehla" },
    { "value": "Sitrah", "label": "Sitrah" },
    { "value": "Tubli", "label": "Tubli" },
    { "value": "Umm an Nasan", "label": "Umm an Nasan" },
    { "value": "Zallaq", "label": "Zallaq" }
];

